spring.application.name=bookstack_backend
# Database stuff
spring.datasource.url=jdbc:postgresql://localhost:5432/bookstack_db
spring.datasource.username=postgres
spring.datasource.password=password

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

bookstack.app.jwtSecret=Zy6teVRrvRrTxnXMwQy6awYO0VYs4U/cGruwYjAkr6Q7XPiFH6ysI8+/hRqLn4g4MwG3eemfN1/MoJuYGOHiSw==
bookstack.app.jwtExpirationMs=86400000

bookstack.app.jwtCookieName=bookstack-jwt
bookstack.app.jwtRefreshCookieName=bookstack-jwt-refresh
bookstack.app.jwtRefreshExpirationMs=86400000